#HeadshotEffects by wesley27 - Configuration

#Do you want HeadShotEffects to only occur in specific worlds? Default is false.
UseSpecificWorlds: false
Worlds:
- world1
- world2
- world3

#ShooterMessage: the message sent to the shooter when they get a headshot.
#Use color codes via '&' and victims name via %victim
ShooterMessage: '&6[Headshot] You have hit %victim with a headshot!'

#Options for extra damage. The ExtraDamage value will make the headshot do its normal
#damage + the value. Instakill will instantly kill the victim. For either of these to
#occur only if the player has a helmet, set HelmOnly to true.
DamageOptions:
    ExtraDamage: 0
    InstaKill: false
    HelmOnly: false

#HeadshotSound: the sound that plays when someone gets a headshot
#All available sounds to use can be found here: http://jd.bukkit.org/rb/apidocs/org/bukkit/Sound.html
#Set to none if you don't want a sound to play when a headshot occurs
HeadshotSound: ZOMBIE_WOODBREAK

#RunCommand: run a command when a player gets a headshot. Default value is none.
#Use colour codes via the & symbol Use %shooter to get the shooters name, use %victim to get the victims name.
RunCommand: none